### ISSUE TITLE
pull from paramaw/chargebee-rails-subscriptions ?

### ISSUE THREAD

**Issue by ConfusedVorlon** [chargebee/chargebee-rails-subscriptions#7]
Hi Folks,

Great that this repo is live again.
there are a couple of nice additions in this fork (it's the one I'm using)
https://github.com/paramaw/chargebee-rails-subscriptions/commits/master

I can't see a way to raise an issue there to suggest they make a pull request. It would be great if you could have a look and incorporate appropriate changes

**Comment by Thirumal-Sakthivel** [comment]
@ConfusedVorlon Can you raise a PR here with the changes from the above mentioned [repo](https://github.com/paramaw/chargebee-rails-subscriptions/commits/master) ?

**Comment by ConfusedVorlon** [comment]
no idea how to do that I'm afraid. It isn't my repo - and github doesn't seem to let me create a pull from a repo I don't own.

**Comment by ConfusedVorlon** [comment]
I figured out how to do this. I have sent the pull request to the spiritle branch (iirc - that's the definitive branch now)

https://github.com/spritlesoftware/chargebee-rails-subscriptions/pull/9

**Comment by sai92messy** [comment]
@ConfusedVorlon thanks for raising PR on spritle repo, will review and merge the PR there. We will close this issue here.
